### ISSUE TITLE
Implement a class to handle API calls to get data about covid-19 world situation

### ISSUE THREAD

**Issue by RcDevRIL** [RcDevRIL/cesi_covid_19_tracker#2]
J'ai déjà commencé, manque plus qu'a choisir une API etc.

Enfin la chu en train d'imposer des trucs, alors on en rediscute cette aprem 😆 

bon app 🍔 👍

**Comment by BoiteSphinx** [comment]
On pourrait partir sur [cette API](https://github.com/ExpDev07/coronavirus-tracker-api), qui récupère les données de propagation du virus par pays, le nombre de guéris, de morts, d'infectés...

**Comment by RcDevRIL** [comment]
En vrai je pense on est presque obligé de mapper la réponse de l'API sur un DTO car ça va vite devenir horrible à manipuler sinon ^^
Je vais voir ça en début d'aprem, ou en tout cas faire en sorte que manipuler la réponse de l'API soit simple, car la je galère un peu
