### ISSUE TITLE
Le champ guéris renvoie 0 depuis plusieurs jours

### ISSUE THREAD

**Issue by RcDevRIL** [RcDevRIL/cesi_covid_19_tracker#20]
Le dev de l’API est au courant et apparemment chercher à changer de source d’infos. A voir pendant la semaine de cours si c encore le cas, laissons le faire le taf :)

**Comment by RcDevRIL** [comment]
Ouaip ben ce sera toujours le cas demain :p

Donc soit on change d’API soit on l’enlève, soit on laisse et on explique que c la source d’info qui plante, ou encore on cherche sur internet le pourcentage moyen de guérison et on affiche une valeur estimée par rapport au nombre de contaminé que nous donne l’API

**Comment by BoiteSphinx** [comment]
Si on change d'API, on peut s'inspirer de [ce repo](https://github.com/singh-saheb/tgd_covid_tracker_app), où le mec à fait ce que l'on souhaite faire !

Il à même mis [une vidéo](https://youtu.be/XFGf_jMJSfw) où il est en train de le coder (1h)
Et oui, c'est encore en indien 😢

**Comment by RcDevRIL** [comment]
aight pourquoi pas, si on a l'équivalent en info, je vais fouiller un peu 'lapi en attendant le prof

**Comment by RcDevRIL** [comment]
du coup chu carrément chaud, elle est très bien

https://corona.lmao.ninja/docs/#/
