### ISSUE TITLE
Add a detailed README.MD

### ISSUE THREAD

**Issue by RcDevRIL** [RcDevRIL/cesi_covid_19_tracker#3]
- Présentation
- Installation
- Contributions
- Versionning
- Auteurs
- License

**Comment by BoiteSphinx** [comment]
Test commntaire

**Comment by FerreiraJames** [comment]
Coucou

**Comment by RcDevRIL** [comment]
J'ai repris le template de notre projet Madera, il répond pas exactement à ce que demande le prof mais c un début de structure. J'ai maj le badge de build seulement et la liste des contributeurs (meme si liens cassés pour james eet quentin).
Donc faut rédiger 2-3 phrases sur la présentation de l'appli !
Installation, c a peu près couvert par ce readme.
Contributions je liste seulement notre équipe, mais c a mettre dans une section "Auteurs" en fait.
Licence a priori c ok !
Versionning on prend celui qu'il nous a présenté? Semantic Versionning 2.0 ?
