### ISSUE TITLE
Duplicate README for english version

### ISSUE THREAD

**Issue by RcDevRIL** [RcDevRIL/cesi_covid_19_tracker#52]

**Comment by CodeSadhu** [comment]
Anybody working on this?

**Comment by RcDevRIL** [comment]
Hello :) thanks for browsing my project !! 🔥😁

No, but you can do a PR if you want, that would be highly appreciated!

I don’t have spare time until the 19/05, but can still review PRs

**Comment by CodeSadhu** [comment]
Sure. Would love to.

**Comment by RcDevRIL** [comment]
Fix an issue of your choice then, as you can see, they’re all « good first issue » 👍🏼
I would love to see the V2.0 alive 😁

**Comment by RcDevRIL** [comment]
Waiting for update of french readme before merging PR
